// ============================================================================
// timingFitSummary.C — the single authoritative POST-FIX four-build (a,b) table.
// Protocol: AUDIT.md (this directory). Uses the PRODUCTION estimator chain
// (timingBrightestK -> post-fix tebSigma + eventDWUP veto + continuous fiducial),
// adopted sources (DSB1/MIXED srCFD, LUAG/TENERGY LED), brightest-1000,
// sigma(E) = sqrt((a/sqrtE)^2 + b^2) with per-point stat errors, PDG sqrt(chi2/ndf)
// error inflation. Emits a markdown table + figure + narrative pass/fail checks.
//   source setup.sh
//   root -l -b -q 'papers/scripts/timing_fit_summary/timingFitSummary.C+'
// Output: papers/tables/timing_fit_summary_2026-06-09.md,
//         papers/figures/timing_fit_summary/timing_fit_summary.png
// ============================================================================
#include "RadView.h"
#include "RadTiming.h"
#include "DataPaths.h"
#include "PlotUtils.h"
#include "TFile.h"
#include "TTree.h"
#include "TGraphErrors.h"
#include "TBox.h"
#include "TF1.h"
#include "TCanvas.h"
#include "TLegend.h"
#include "TLatex.h"
#include "TStyle.h"
#include "TSystem.h"
#include <vector>
#include <fstream>
#include <cmath>
#include <cstdio>
using namespace rad;

struct BRow {
    const char* build; const char* wls; int src; const char* srcName;
    std::vector<double> E,S,Se; double light150=0; double s150=-1, e150=0;
    double a=0,ae=0,b=0,be=0,chi=0; int ndf=0; bool mono=true;
};

void timingFitSummary(){
    ApplyRADiCALStyle(); gStyle->SetOptStat(0); gStyle->SetGridStyle(3); gStyle->SetGridColor(kGray);
    gSystem->mkdir("papers/tables",kTRUE); gSystem->mkdir("papers/figures/timing_fit_summary",kTRUE);
    const double Es[6]={25,50,75,100,125,150};
    BRow rows[4]={
        {"DSB1","DSB1 organic (4x T-type)",RadView::kLGCFD,"srCFD"},
        {"LUAG","LuAG:Ce ceramic (4x T-type)",RadView::kLED,"LED"},
        {"MIXED","2x DSB1 + 2x LuAG:Ce",RadView::kLGCFD,"srCFD (module-wide; ill-posed, see note)"},
        {"TENERGY","3x DSB1 T-type + 1x E-type",RadView::kLED,"LED"}};
    printf("\n===== POST-FIX four-build timing fit summary (production estimator) =====\n");
    for(auto& r:rows){
        BuildConfig cfg=BuildConfig::Load(radConfig(r.build).Data());
        for(double e:Es){ TString p=radReduced(r.build,e); if(gSystem->AccessPathName(p.Data())) continue;
            TFile* f=TFile::Open(p.Data()); if(!f||f->IsZombie()){if(f)f->Close();continue;}
            TTree* t=(TTree*)f->Get("rad"); if(!t){f->Close();continue;}
            RadView v; v.attach(t,&cfg);
            TimingResult tr=timingBrightestK(v,e,r.src,1000);
            if(tr.sigma_ps>0){ r.E.push_back(e); r.S.push_back(tr.sigma_ps);
                r.Se.push_back(tr.sigma_ps/std::sqrt(2000.0));
                if(e>149){ r.s150=tr.sigma_ps; r.e150=tr.sigma_ps/std::sqrt(2000.0); r.light150=tr.bestE; } }
            f->Close(); }
        for(size_t i=1;i<r.S.size();++i) if(r.S[i]>r.S[i-1]+0.1) r.mono=false;
        if(r.E.size()>=3){ std::vector<double> ze(r.E.size(),0);
            TGraphErrors g(r.E.size(),&r.E[0],&r.S[0],&ze[0],&r.Se[0]);
            TF1 f("f","sqrt([0]*[0]/x+[1]*[1])",r.E.front(),r.E.back());
            f.SetParameters(300,18); g.Fit(&f,"QN");
            r.a=std::fabs(f.GetParameter(0)); r.ae=f.GetParError(0);
            r.b=std::fabs(f.GetParameter(1)); r.be=f.GetParError(1);
            r.chi=f.GetChisquare(); r.ndf=f.GetNDF();
            if(r.ndf>0&&r.chi/r.ndf>1){ double s=std::sqrt(r.chi/r.ndf); r.ae*=s; r.be*=s; } }
        printf("  %-8s %-7s: ",r.build,r.srcName);
        for(size_t i=0;i<r.S.size();++i) printf("%5.1f ",r.S[i]);
        printf(" | a=%.0f+-%.0f b=%.1f+-%.1f chi2/ndf=%.1f/%d %s L150=%.0f\n",
               r.a,r.ae,r.b,r.be,r.chi,r.ndf,r.mono?"MONO":"(NM)",r.light150);
    }
    // narrative checks
    double aR = rows[1].a/std::max(1.0,rows[0].a);
    printf("\n  narrative checks: a_DSB1=%.0f (target ~200)  a_LuAG=%.0f (~455)  ratio=%.2f (~2.3)\n",
           rows[0].a,rows[1].a,aR);
    printf("  b: DSB1 %.1f+-%.1f, LuAG %.1f+-%.1f, TENERGY %.1f+-%.1f (shared ~20?)\n",
           rows[0].b,rows[0].be,rows[1].b,rows[1].be,rows[3].b,rows[3].be);
    printf("  best measured sigma(150): DSB1 %.1f+-%.1f ps (floor verb stays 'confirms 17.5')\n",
           rows[0].s150,rows[0].e150);

    // ---- markdown table ----
    std::ofstream md("papers/tables/timing_fit_summary_2026-06-09.md");
    md << "# Four-build timing fit summary — POST-FIX production estimator (2026-06-09)\n\n";
    md << "Generated by `papers/scripts/timing_fit_summary/timingFitSummary.C` (audit: AUDIT.md).\n";
    md << "Estimator chain: brightest-1000 (DW−UP)/2, post-fix tebSigma (robust window + tail guard)\n";
    md << "+ in-event channel-consistency veto + continuous fiducial. Fit σ(E)=√((a/√E)²+b²) over the\n";
    md << "measured span; errors are per-point statistical (σ/√2000) with √(χ²/ndf) inflation.\n";
    md << "THIS TABLE SUPERSEDES all pre-fix (a,b) values (201/19.5, 455/19.8, 233/34.6, 240/22).\n\n";
    md << "| build | WLS configuration | source | light proxy ⟨sum_lg⟩@150 (mV) | a (ps·√GeV) | b (ps) | χ²/ndf | σ(150) meas. (ps) | monotonic | notes |\n";
    md << "|---|---|---|---|---|---|---|---|---|---|\n";
    const char* notes[4]={
        "headline build; 25–150 GeV",
        "best measured point is σ(150); floor is an extrapolation (b err large)",
        "module-wide single estimator is ILL-POSED (mixed clip regimes); paper treats MIXED per material (GATE 6)",
        "3 timing capillaries (√(4/3) statistical penalty vs 4-cap builds)"};
    char buf[512];
    for(int i=0;i<4;++i){ BRow& r=rows[i];
        snprintf(buf,sizeof(buf),"| %s | %s | %s | %.0f | %.0f ± %.0f | %.1f ± %.1f | %.1f/%d | %.1f ± %.1f | %s | %s |\n",
            r.build,r.wls,r.srcName,r.light150,r.a,r.ae,r.b,r.be,r.chi,r.ndf,r.s150,r.e150,
            r.mono?"yes":"NO",notes[i]);
        md << buf; }
    md << "\n## Narrative checks (old story vs post-fix recompute)\n\n";
    snprintf(buf,sizeof(buf),
      "- a_DSB1 = %.0f ± %.0f (was ~201): %s\n- a_LuAG = %.0f ± %.0f (was ~455): %s\n"
      "- cross-build a-ratio = %.2f (was ~2.3): %s\n"
      "- floors: DSB1 %.1f±%.1f / LuAG %.1f±%.1f / TENERGY %.1f±%.1f ps (\"shared ~20 ps\" %s)\n"
      "- best measured σ(150 GeV) = %.1f ± %.1f ps (DSB1, srCFD, brightest-1000; was quoted 25.3 pre-fix)\n"
      "- floor language: REMAINS \"consistent with / confirms the published 17.5 ps\" — never \"measures\"\n",
      rows[0].a,rows[0].ae, std::fabs(rows[0].a-201)<25?"HOLDS":"SHIFTED — narrative updated",
      rows[1].a,rows[1].ae, std::fabs(rows[1].a-455)<60?"HOLDS":"SHIFTED — narrative updated",
      aR, (aR>2.0&&aR<2.6)?"HOLDS":"SHIFTED — narrative updated",
      rows[0].b,rows[0].be,rows[1].b,rows[1].be,rows[3].b,rows[3].be,
      (std::fabs(rows[0].b-20)<4&&std::fabs(rows[1].b-20)<8)?"HOLDS":"REVISIT",
      rows[0].s150,rows[0].e150);
    md << buf;
    md << "- MIXED module-wide row: reference only; the publishable MIXED results are the per-material\n";
    md << "  GATE-6 paired comparison (1.04 ± 0.05) and the per-material diagonals.\n";
    md.close();
    printf("  wrote papers/tables/timing_fit_summary_2026-06-09.md\n");

    // ---- figure (publication style: requirement bands, MIXED as grey reference) ----
    TCanvas* c=new TCanvas("tfs","",1000,760);
    c->SetLeftMargin(0.12);c->SetRightMargin(0.04);c->SetTopMargin(0.04);c->SetBottomMargin(0.13);c->SetGridy();
    TH1F* fr=c->DrawFrame(15,12,165,85);
    fr->SetTitle(";beam energy E (GeV);brightest-1000 (DW#minusUP)/2  #sigma_{t} (ps)");
    fr->GetYaxis()->SetTitleSize(0.045);fr->GetYaxis()->SetTitleOffset(1.25);fr->GetXaxis()->SetTitleSize(0.045);
    // per-MIP/track comparator bands (context only; cited in the text): BTL 30-60, HGTD 35-50
    TBox* bBTL=new TBox(15,30,165,60); bBTL->SetFillColorAlpha(kOrange+1,0.10); bBTL->Draw();
    TBox* bHGTD=new TBox(15,35,165,50); bHGTD->SetFillColorAlpha(kOrange+1,0.10); bHGTD->Draw();
    TLatex bt; bt.SetTextSize(0.026); bt.SetTextColor(kOrange+3);
    bt.DrawLatex(18,57,"CMS BTL 30#minus60 ps (per track)"); bt.DrawLatex(18,52.5,"ATLAS HGTD 35#minus50 ps (per hit)");
    // MIXED drawn first, dashed grey, reference-only
    int ord[4]={2,0,1,3};
    int cols[4]={kRData,kRGreen+1,kGray+2,kOrange+8}; int mks[4]={20,21,24,23};
    TLegend* lg=new TLegend(0.47,0.66,0.96,0.93); lg->SetBorderSize(0);lg->SetFillStyle(0);lg->SetTextSize(0.031);
    for(int k=0;k<4;++k){ int i=ord[k]; BRow& r=rows[i]; if(r.E.size()<3) continue;
        bool mixed=(i==2);
        std::vector<double> ze(r.E.size(),0);
        TGraphErrors* g=new TGraphErrors(r.E.size(),&r.E[0],&r.S[0],&ze[0],&r.Se[0]);
        g->SetMarkerStyle(mks[i]);g->SetMarkerColor(cols[i]);g->SetLineColor(cols[i]);g->SetMarkerSize(mixed?1.2:1.5);
        TF1* f=new TF1(Form("ff%d",i),"sqrt([0]*[0]/x+[1]*[1])",r.E.front(),r.E.back());
        f->SetParameters(r.a,r.b); f->SetLineColor(cols[i]); f->SetLineWidth(mixed?2:3);
        f->SetLineStyle(mixed?7:1); f->Draw("SAME");
        g->Draw("P SAME"); }
    // legend in physical order
    for(int i=0;i<4;++i){ BRow& r=rows[i];
        TGraphErrors* gl=new TGraphErrors(); gl->SetMarkerStyle(mks[i]);gl->SetMarkerColor(cols[i]);gl->SetLineColor(cols[i]);
        gl->SetLineStyle(i==2?7:1); gl->SetLineWidth(i==2?2:3);
        lg->AddEntry(gl,Form("%s%s: a=%.0f#pm%.0f, b=%.1f#pm%.1f",r.build,
            i==2?"*":Form(" (%s)",r.srcName),r.a,r.ae,r.b,r.be),"lp"); }
    lg->Draw();
    TLatex tx; tx.SetNDC(); tx.SetTextSize(0.026); tx.SetTextColor(kGray+3);
    tx.DrawLatex(0.40,0.585,"*single-estimator timing is ill-posed for MIXED (Sec. 6)");
    // paper convention (format pass 2026-06-09): no internal super-title; the LaTeX caption carries it
    c->Print("papers/figures/timing_fit_summary/timing_fit_summary.png");
    c->Print("papers/timing/figs/thesis_postfix.png");
    c->Print("papers/timing/figs/thesis_postfix.pdf");
    printf("  wrote timing_fit_summary.png + papers/timing/figs/thesis_postfix.{png,pdf}\n");
}
